In [1]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\ajay\anaconda3\lib\site-packages (1.1.1)Note: you may need to restart the kernel to use updated packages.

In [220]:
import pymysql

myconnection=pymysql.connect(host='localhost',user='root',password='Theja@22', database='project_nasa')


mycursor=myconnection.cursor()
print("Mysql Connected Successfully")
mycursor.execute("create database IF NOT EXISTS Project_nasa")
print("Database Project_nasa Connected Successfully !!")

Mysql Connected Successfully
Database Project_nasa Connected Successfully !!

In [45]:
import pandas as pd

In [9]:
mycursor.execute('show databases')
for db in mycursor:
    print(db)

('guvi',)
('information_schema',)
('mysql',)
('performance_schema',)
('project_nasa',)
('sakila',)
('sys',)
('world',)

In [13]:
mycursor.execute('use  project_nasa')

0

In [19]:
mycursor.execute('desc asteroids')
for desc in mycursor:
    print(desc)

('id', 'int', 'YES', '', None, '')
('name', 'varchar(50)', 'YES', '', None, '')
('absolute_magnitude_h', 'float', 'YES', '', None, '')
('estimated_diameter_min_km', 'float', 'YES', '', None, '')
('estimated_diameter_max_km', 'float', 'YES', '', None, '')
('is_potentially_hazardous_asteroid', 'tinyint(1)', 'YES', '', None, '')

In [81]:
mycursor.execute("select * from asteroids;")
for row in mycursor:
    print(row)

(3373919, '(2007 GW4)', 20.6, 0.20163, 0.450858, 0)
(54110077, '(2021 CR1)', 25.1, 0.0253837, 0.0567597, 0)
(54138303, '(2021 GT16)', 27.4, 0.00880146, 0.0196807, 0)
(54144240, '(2021 JZ2)', 22.91, 0.0695913, 0.155611, 0)
(54421069, '(2024 BF)', 24.46, 0.0340843, 0.0762149, 0)
(54527149, '(2025 GT1)', 24.973, 0.0269126, 0.0601783, 0)
(54527284, '(2025 HE1)', 24.414, 0.0348141, 0.0778467, 0)
(54527292, '(2025 HN1)', 25.366, 0.0224572, 0.0502158, 0)
(54527390, '(2025 HF2)', 24.516, 0.0332166, 0.0742745, 0)
(54527597, '(2025 HP3)', 23.845, 0.0452434, 0.101167, 0)
(54528735, '(2025 JB)', 27.509, 0.00837057, 0.0187172, 0)
(54528916, '(2025 JF)', 28.543, 0.00519942, 0.0116263, 0)
(3485809, '(2010 AO60)', 21.75, 0.118728, 0.265485, 0)
(3634275, '(2013 GF23)', 23.7, 0.0483676, 0.108153, 0)
(3774574, '(2017 JJ2)', 25.1, 0.0253837, 0.0567597, 0)
(54073370, '(2020 UX)', 31.14, 0.00157237, 0.00351593, 0)
(54135427, '(2021 GP3)', 24.11, 0.0400456, 0.0895447, 0)
(54142841, '(2021 JO)', 21.63, 0.125474, 0.280569, 0)
(54161068, '(2021 MD)', 23.53, 0.0523064, 0.116961, 0)
(54317869, '(2022 UX3)', 22.93, 0.0689533, 0.154184, 0)
(54335008, '(2022 YH)', 24.8, 0.0291444, 0.0651688, 0)
(54352572, '(2023 FC6)', 20.61, 0.200704, 0.448787, 1)
(54439998, '(2024 JM2)', 23.78, 0.0466181, 0.104241, 0)
(54527741, '(2025 HR5)', 25.331, 0.0228221, 0.0510317, 0)
(54529110, '(2025 JD1)', 25.005, 0.0265189, 0.059298, 0)
(54529316, '(2025 JT1)', 23.667, 0.0491083, 0.10981, 0)
(54529548, '(2025 JV1)', 26.193, 0.0153446, 0.0343115, 0)
(54529727, '(2025 JG2)', 25.525, 0.0208716, 0.0466702, 0)
(3180147, '(2004 HQ1)', 23.47, 0.0537718, 0.120238, 0)
(3468431, '(2009 SA100)', 23.9, 0.0441118, 0.098637, 0)
(3627059, '(2013 DF)', 24.6, 0.0319562, 0.0714562, 0)
(3670293, '(2014 HS184)', 23.3, 0.0581507, 0.130029, 0)
(3748562, '(2016 GB1)', 21.46, 0.135692, 0.303417, 0)
(3831479, '(2018 TF3)', 20.51, 0.210162, 0.469937, 1)
(3841529, '(2019 HO)', 23.98, 0.0425163, 0.0950692, 0)
(3841721, '(2019 JV1)', 22.97, 0.0676947, 0.15137, 0)
(54135432, '(2021 GU3)', 26.9, 0.0110804, 0.0247765, 0)
(54139086, '(2021 HV1)', 19.87, 0.282199, 0.631015, 0)
(54212592, '(2021 UL1)', 24.66, 0.0310853, 0.0695088, 0)
(54239841, '(2022 BH1)', 20.91, 0.174805, 0.390877, 1)
(54251532, '(2022 EA3)', 27.31, 0.00917392, 0.0205135, 0)
(54317171, '(2022 UW1)', 23.54, 0.0520661, 0.116423, 0)
(54527376, '(2025 HR1)', 27.112, 0.0100497, 0.0224719, 0)
(54527736, '(2025 HJ5)', 26.825, 0.0114698, 0.0256472, 0)
(54528530, '(2025 HP22)', 28.492, 0.00532298, 0.0119025, 0)
(54528531, '(2025 JA)', 28.121, 0.00631473, 0.0141202, 0)
(54528918, '(2025 JJ)', 26.248, 0.0149608, 0.0334534, 0)
(54528921, '(2025 JL)', 24.205, 0.0383314, 0.0857117, 0)
(3076550, '(2000 WL63)', 19.8, 0.291444, 0.651688, 0)
(3465236, '(2009 OS5)', 24.4, 0.0350393, 0.0783502, 0)
(3841713, '(2019 JM1)', 24.0, 0.0421265, 0.0941976, 0)
(3971134, '(2020 AK)', 19.12, 0.398616, 0.891333, 0)
(54100620, '(2020 YF)', 28.82, 0.00457673, 0.0102339, 0)
(54216314, '(2021 VH2)', 28.8, 0.00461907, 0.0103286, 0)
(54278174, '(2022 JP)', 23.43, 0.0547715, 0.122473, 0)
(54289654, '(2022 ND)', 25.32, 0.022938, 0.0512909, 0)
(54291604, '(2022 OW1)', 25.93, 0.0173203, 0.0387293, 0)
(54397455, '(2023 UR3)', 26.27, 0.01481, 0.0331162, 0)
(54430725, '(2024 ET3)', 28.39, 0.00557898, 0.012475, 0)
(54439891, '(2024 JD2)', 24.63, 0.0315177, 0.0704758, 0)
(54487074, '(2024 TC2)', 26.54, 0.0130784, 0.0292442, 0)
(54524518, '(2025 FA6)', 23.62, 0.0501828, 0.112212, 0)
(54524526, '(2025 FK6)', 23.12, 0.0631764, 0.141267, 0)
(54525640, '(2025 FJ18)', 24.23, 0.0378927, 0.0847305, 0)
(54529552, '(2025 JZ1)', 22.862, 0.0711467, 0.159089, 0)
(3348144, '(2006 TL)', 23.9, 0.0441118, 0.098637, 0)
(3460325, '(2009 KY1)', 23.84, 0.0453477, 0.1014, 0)
(3883096, '(2019 UU7)', 26.03, 0.0165407, 0.0369862, 0)
(3942366, '(2019 YO)', 26.5, 0.0133216, 0.0297879, 0)
(54017159, '(2020 JN3)', 27.4, 0.00880146, 0.0196807, 0)
(54017292, '(2020 KR6)', 20.04, 0.260949, 0.583499, 0)
(54051050, '(2020 PY2)', 26.5, 0.0133216, 0.0297879, 0)
(54054611, '(2020 SM4)', 27.7, 0.00766576, 0.0171412, 0)
(54203700, '(2021 TR3)', 25.43, 0.0218049, 0.0487573, 0)
(54291306, '(2022 ON1)', 24.42, 0.034718, 0.0776319, 0)
(54386830, '(2023 SJ4)', 25.32, 0.022938, 0.0512909, 0)
(54527378, '(2025 HT1)', 24.164, 0.039062, 0.0873454, 0)
(54527596, '(2025 HN3)', 25.386, 0.0222513, 0.0497554, 0)
(54528922, '(2025 JM)', 25.311, 0.0230332, 0.0515039, 0)
(3092201, '(1998 VE31)', 21.07, 0.162388, 0.363111, 0)
(3553988, '(2010 XR69)', 25.4, 0.0221083, 0.0494356, 0)
(3608565, '(2012 RH10)', 22.11, 0.10059, 0.224926, 0)
(3789741, '(2017 WY27)', 27.9, 0.00699125, 0.0156329, 0)
(54100286, '(2020 XA6)', 24.11, 0.0400456, 0.0895447, 0)
(54266164, '(2022 FZ3)', 28.88, 0.004452, 0.00995497, 0)
(54357785, '(2023 JX)', 22.74, 0.0752584, 0.168283, 0)
(54527451, '(2025 HY2)', 24.865, 0.0282849, 0.063247, 0)
(54529314, '(2025 JQ1)', 24.464, 0.0340216, 0.0760747, 0)
(54529728, '(2025 JF2)', 25.96, 0.0170826, 0.0381979, 0)
(2387733, '387733 (2003 GS)', 18.98, 0.425163, 0.950692, 0)
(2529951, '529951 (2010 UD)', 21.08, 0.161642, 0.361443, 1)
(3719196, '(2015 JR1)', 26.1, 0.016016, 0.0358129, 0)
(3752902, '(2016 JG12)', 22.55, 0.0821401, 0.183671, 0)
(3774095, '(2017 HQ3)', 25.71, 0.019167, 0.0428588, 0)
(3843051, '(2019 MG2)', 22.14, 0.0992099, 0.22184, 0)
(54143421, '(2021 JG1)', 24.76, 0.0296862, 0.0663804, 0)
(54143552, '(2021 JN1)', 24.77, 0.0295498, 0.0660754, 0)
(54200306, '(2021 SV1)', 26.48, 0.0134448, 0.0300635, 0)
(54280486, '(2022 KU3)', 23.0, 0.0667659, 0.149293, 0)
(54492950, '(2024 TU20)', 24.7, 0.0305179, 0.0682402, 0)
(54527735, '(2025 HF5)', 25.796, 0.0184228, 0.0411946, 0)
(54528046, '(2025 HZ6)', 24.65, 0.0312288, 0.0698297, 0)
(54528919, '(2025 JK)', 26.614, 0.0126402, 0.0282644, 0)
(54529553, '(2025 JA2)', 23.277, 0.0587699, 0.131414, 0)
(54534095, '(2025 KH13)', 25.671, 0.0195144, 0.0436355, 0)
(3550117, '(2010 VB)', 25.6, 0.020163, 0.0450858, 0)
(54016819, '(2020 HT8)', 28.6, 0.00506471, 0.011325, 0)
(54017094, '(2020 KA1)', 26.7, 0.0121494, 0.0271669, 0)
(54075984, '(2020 UM3)', 24.3, 0.0366906, 0.0820427, 0)
(54138707, '(2021 HZ)', 25.37, 0.0224158, 0.0501233, 0)
(54199511, '(2021 RR23)', 20.52, 0.209197, 0.467778, 1)
(54354970, '(2023 HV2)', 24.8, 0.0291444, 0.0651688, 0)
(54385807, '(2023 SK3)', 25.87, 0.0178055, 0.0398144, 0)
(54527656, '(2025 HU4)', 23.917, 0.0437678, 0.0978678, 0)
(54528737, '(2025 JE)', 28.632, 0.00499063, 0.0111594, 0)
(54529312, '(2025 JO1)', 23.486, 0.0533771, 0.119355, 0)
(54533093, '(2025 KN1)', 24.432, 0.0345267, 0.077204, 0)
(54533420, '(2025 KD4)', 24.675, 0.0308713, 0.0690303, 0)
(3151655, '(2003 FY6)', 22.61, 0.0799015, 0.178665, 0)
(3703548, '(2015 AP44)', 26.2, 0.0152952, 0.0342011, 0)
(3736517, '(2015 XY261)', 27.2, 0.00965062, 0.0215794, 0)
(54054748, '(2020 TG)', 25.61, 0.0200704, 0.0448787, 0)
(54146075, '(2021 KH)', 26.35, 0.0142743, 0.0319183, 0)
(54151573, '(2021 KZ2)', 25.24, 0.0237988, 0.0532157, 0)
(54248949, '(2022 EO)', 29.49, 0.00336167, 0.00751692, 0)
(54358912, '(2023 JF5)', 23.67, 0.0490405, 0.109658, 0)
(54373546, '(2023 ML)', 23.0, 0.0667659, 0.149293, 0)
(54527379, '(2025 FE29)', 24.096, 0.0403046, 0.0901239, 0)
(54527450, '(2025 HX2)', 24.368, 0.0355594, 0.0795133, 0)
(54528923, '(2025 JO)', 27.006, 0.0105525, 0.0235961, 0)
(54529103, '(2025 JU)', 23.28, 0.0586888, 0.131232, 0)
(54529311, '(2025 JK1)', 26.511, 0.0132542, 0.0296374, 0)
(54529549, '(2025 JW1)', 25.954, 0.0171299, 0.0383036, 0)
(54529550, '(2025 JX1)', 25.346, 0.022665, 0.0506804, 0)
(54529697, '(2025 JC2)', 21.613, 0.126461, 0.282774, 0)
(54529811, '(2025 JH2)', 27.074, 0.0102272, 0.0228686, 0)
(3564142, '(2011 HJ7)', 22.39, 0.0884209, 0.197715, 0)
(3582867, '(2011 UY114)', 23.65, 0.0494943, 0.110673, 0)
(3752720, '(2016 HT19)', 23.0, 0.0667659, 0.149293, 0)
(3752703, '(2016 JE)', 21.87, 0.112345, 0.251212, 0)
(3774133, '(2017 HA5)', 27.5, 0.00840533, 0.0187949, 0)
(3795061, '(2017 YZ4)', 28.1, 0.0063761, 0.0142574, 0)
(3841764, '(2019 JV2)', 23.0, 0.0667659, 0.149293, 0)
(3878618, '(2019 TK5)', 27.46, 0.0085616, 0.0191443, 0)
(54016947, '(2020 JB)', 23.5, 0.0530341, 0.118588, 0)
(54279925, '(2022 KX)', 25.73, 0.0189913, 0.0424659, 0)
(54280490, '(2022 KB4)', 24.32, 0.0363542, 0.0812905, 0)
(54490134, '(2024 TX9)', 26.38, 0.0140785, 0.0314804, 0)
(54524049, '(2025 FV)', 22.47, 0.0852226, 0.190564, 0)
(54527738, '(2025 HN5)', 22.277, 0.093144, 0.208276, 0)
(54529106, '(2025 JA1)', 25.472, 0.0213873, 0.0478233, 0)
(2523809, '523809 (2007 TV18)', 23.79, 0.046404, 0.103762, 0)
(3182181, '(2004 JP12)', 23.4, 0.0555335, 0.124177, 0)
(3653907, '(2013 WY43)', 26.7, 0.0121494, 0.0271669, 0)
(3683472, '(2014 QZ295)', 24.8, 0.0291444, 0.0651688, 0)
(3695293, '(2014 UH175)', 20.45, 0.21605, 0.483103, 0)
(3735392, '(2015 WA1)', 21.82, 0.114962, 0.257063, 0)
(54221204, '(2021 VW22)', 26.82, 0.0114962, 0.0257063, 0)
(54280290, '(2022 KF3)', 27.07, 0.010246, 0.0229108, 0)
(54440314, '(2024 JG3)', 22.67, 0.077724, 0.173796, 0)
(54529551, '(2025 JY1)', 25.067, 0.0257724, 0.0576289, 0)
(54532560, '(2025 KB)', 24.659, 0.0310996, 0.0695409, 0)
(3829424, '(2018 RO5)', 25.61, 0.0200704, 0.0448787, 0)
(3830890, '(2018 SP2)', 24.8, 0.0291444, 0.0651688, 0)
(54017163, '(2020 KS2)', 24.4, 0.0350393, 0.0783502, 0)
(54076351, '(2020 UT4)', 28.22, 0.0060333, 0.0134909, 0)
(54216182, '(2021 VK1)', 24.55, 0.0327005, 0.0731206, 0)
(54379768, '(2023 RC)', 23.41, 0.0552783, 0.123606, 0)
(54445454, '(2024 KB2)', 23.53, 0.0523064, 0.116961, 0)
(54524048, '(2025 DT50)', 22.65, 0.0784431, 0.175404, 0)
(54532400, '(2025 JL2)', 21.612, 0.126519, 0.282905, 0)
(3596097, '(2011 YU74)', 22.99, 0.0670741, 0.149982, 0)
(3703538, '(2015 AA44)', 23.9, 0.0441118, 0.098637, 0)
(3728898, '(2015 TF)', 22.14, 0.0992099, 0.22184, 0)
(3893340, '(2019 VD6)', 23.14, 0.0625972, 0.139972, 0)
(54297620, '(2022 QO4)', 24.93, 0.0274508, 0.0613819, 0)
(54528330, '(2025 HV18)', 23.53, 0.0523064, 0.116961, 0)
(54533095, '(2025 KQ1)', 24.116, 0.0399351, 0.0892976, 0)
(2154276, '154276 (2002 SY50)', 17.64, 0.788052, 1.76214, 1)
(3278078, '(2005 JU81)', 21.79, 0.116561, 0.260639, 1)
(3669249, '(2014 HB124)', 23.02, 0.0661538, 0.147924, 0)
(3671001, '(2014 JA31)', 23.6, 0.0506471, 0.11325, 0)
(3672457, '(2014 KC39)', 23.3, 0.0581507, 0.130029, 0)
(3764838, '(2016 WR8)', 27.4, 0.00880146, 0.0196807, 0)
(3989263, '(2020 BP11)', 26.8, 0.0116026, 0.0259442, 0)
(54016782, '(2020 HM7)', 25.8, 0.0183889, 0.0411188, 0)
(54139088, '(2021 GM26)', 25.72, 0.019079, 0.0426619, 0)
(54219282, '(2021 VK10)', 26.04, 0.0164647, 0.0368163, 0)
(54278350, '(2022 JQ1)', 26.21, 0.0152249, 0.034044, 0)
(54358378, '(2023 JF2)', 24.61, 0.0318094, 0.0711279, 0)
(54383809, '(2023 RY15)', 27.98, 0.00673837, 0.0150675, 0)
(54492233, '(2024 TK20)', 21.36, 0.142087, 0.317717, 0)
(54533324, '(2025 KG3)', 25.479, 0.0213184, 0.0476694, 0)
(54533502, '(2025 KR4)', 25.946, 0.0171931, 0.038445, 0)
(2449089, '449089 (2012 SC22)', 20.14, 0.249204, 0.557237, 0)
(3124996, '(2002 JX8)', 20.43, 0.218049, 0.487573, 1)
(3529624, '(2010 LL68)', 22.88, 0.0705594, 0.157776, 0)
(3703059, '(2014 YE15)', 28.3, 0.00581507, 0.0130029, 0)
(3776269, '(2017 MM8)', 22.58, 0.081013, 0.181151, 0)
(3792427, '(2017 XN61)', 22.37, 0.0892391, 0.199545, 0)
(3797690, '(2018 AF12)', 21.79, 0.116561, 0.260639, 0)
(54049794, '(2020 OY4)', 30.35, 0.00226232, 0.00505871, 0)
(54216373, '(2021 VX3)', 25.68, 0.0194337, 0.043455, 0)
(2612356, '612356 (2002 JX8)', 20.33, 0.228326, 0.510552, 1)
(54278143, '(2022 JO)', 25.81, 0.0183044, 0.0409298, 0)
(54496384, '(2024 UW6)', 26.97, 0.0107289, 0.0239905, 0)
(54524505, '(2025 DJ53)', 18.89, 0.443154, 0.990923, 0)
(54527593, '(2025 HK3)', 23.353, 0.0567486, 0.126894, 0)
(54529554, '(2025 JB2)', 26.335, 0.0143733, 0.0321396, 0)
(54532954, '(2025 KV)', 23.842, 0.0453059, 0.101307, 0)
(54533317, '(2025 KW2)', 25.098, 0.0254071, 0.056812, 0)
(3550117, '(2010 VB)', 25.6, 0.020163, 0.0450858, 0)
(54016819, '(2020 HT8)', 28.6, 0.00506471, 0.011325, 0)
(54017094, '(2020 KA1)', 26.7, 0.0121494, 0.0271669, 0)
(54075984, '(2020 UM3)', 24.3, 0.0366906, 0.0820427, 0)
(54138707, '(2021 HZ)', 25.37, 0.0224158, 0.0501233, 0)
(54199511, '(2021 RR23)', 20.52, 0.209197, 0.467778, 1)
(54354970, '(2023 HV2)', 24.8, 0.0291444, 0.0651688, 0)
(54385807, '(2023 SK3)', 25.87, 0.0178055, 0.0398144, 0)
(54527656, '(2025 HU4)', 23.917, 0.0437678, 0.0978678, 0)
(54528737, '(2025 JE)', 28.632, 0.00499063, 0.0111594, 0)
(54529312, '(2025 JO1)', 23.486, 0.0533771, 0.119355, 0)
(54533093, '(2025 KN1)', 24.432, 0.0345267, 0.077204, 0)
(54533420, '(2025 KD4)', 24.675, 0.0308713, 0.0690303, 0)
(3370167, '(2007 EF)', 21.4, 0.139494, 0.311918, 1)
(3472549, '(2009 UK20)', 26.3, 0.0146068, 0.0326618, 0)
(3753718, '(2016 LJ8)', 25.2, 0.0242412, 0.0542051, 0)
(3843572, '(2019 QG)', 21.36, 0.142087, 0.317717, 1)
(54051164, '(2020 PG6)', 26.9, 0.0110804, 0.0247765, 0)
(54138698, '(2021 HR)', 25.8, 0.0183889, 0.0411188, 0)
(54215208, '(2021 VJ)', 24.96, 0.0270742, 0.0605397, 0)
(2613726, '613726 (2007 EF)', 21.34, 0.143402, 0.320656, 1)
(54341559, '(2023 CS2)', 28.05, 0.00652462, 0.0145895, 0)
(54482429, '(2024 SO2)', 27.9, 0.00699125, 0.0156329, 0)
(54485066, '(2024 SG5)', 24.37, 0.0355267, 0.0794401, 0)
(54528327, '(2025 HM15)', 22.319, 0.0913598, 0.204287, 0)
(54532864, '(2025 KF)', 27.1, 0.0101054, 0.0225964, 0)
(54532947, '(2025 KO)', 25.113, 0.0252322, 0.0564209, 0)
(54532961, '(2025 KB1)', 25.277, 0.0233967, 0.0523167, 0)
(54533161, '(2025 KF2)', 31.359, 0.00142153, 0.00317863, 0)
(54533603, '(2025 KS6)', 24.125, 0.0397699, 0.0889283, 0)
(54533605, '(2025 KW6)', 25.137, 0.0249548, 0.0558007, 0)
(2524471, '524471 (2002 JW15)', 20.43, 0.218049, 0.487573, 0)
(3427460, '(2008 ST)', 27.1, 0.0101054, 0.0225964, 0)
(3653694, '(2013 VO13)', 22.76, 0.0745684, 0.16674, 0)
(3720359, '(2015 KU121)', 22.9, 0.0699125, 0.156329, 0)
(3791307, '(2017 UM52)', 29.53, 0.00330031, 0.00737972, 0)
(3837644, '(2019 AY3)', 23.82, 0.0457673, 0.102339, 0)
(3841669, '(2019 HF4)', 27.6, 0.00802703, 0.017949, 0)
(3972422, '(2020 AW)', 28.73, 0.0047704, 0.0106669, 0)
(54016805, '(2020 HS7)', 29.1, 0.00402305, 0.0089958, 0)
(54017665, '(2020 MR3)', 22.7, 0.0766576, 0.171412, 0)
(54350417, '(2023 EZ2)', 25.55, 0.0206326, 0.046136, 0)
(54527744, '(2025 HD6)', 25.24, 0.0237988, 0.0532157, 0)
(54529112, '(2025 JE1)', 25.853, 0.0179455, 0.0401273, 0)
(54534097, '(2025 KK13)', 23.205, 0.0607512, 0.135844, 0)
(3550134, '(2010 VK)', 21.3, 0.146068, 0.326618, 0)
(3561029, '(2011 GE3)', 25.88, 0.0177237, 0.0396315, 0)
(3672907, '(2014 KV76)', 21.06, 0.163138, 0.364788, 0)
(3719730, '(2015 KB57)', 22.3, 0.0921627, 0.206082, 0)
(3752080, '(2016 HB)', 24.4, 0.0350393, 0.0783502, 0)
(54145088, '(2021 JZ5)', 28.35, 0.0056827, 0.0127069, 0)
(54356988, '(2023 HP5)', 27.63, 0.0079169, 0.0177027, 0)
(54357462, '(2023 JR)', 23.93, 0.0435066, 0.0972837, 0)
(54427459, '(2024 BY15)', 26.78, 0.0117099, 0.0261842, 0)
(54528926, '(2025 JS)', 21.889, 0.111367, 0.249023, 0)
(54532866, '(2025 KH)', 27.387, 0.00885432, 0.0197989, 0)
(54533098, '(2025 KS1)', 26.766, 0.0117857, 0.0263536, 0)
(54533158, '(2025 KZ1)', 27.108, 0.0100683, 0.0225133, 0)
(54533318, '(2025 KX2)', 29.892, 0.00279354, 0.00624655, 0)
(3120863, '(2002 GQ)', 26.3, 0.0146068, 0.0326618, 0)
(3590076, '(2011 XD)', 24.0, 0.0421265, 0.0941976, 0)
(3789456, '(2017 WP)', 23.1, 0.063761, 0.142574, 0)
(3827172, '(2018 RC1)', 26.45, 0.0136319, 0.0304818, 0)
(3831063, '(2018 SF3)', 25.31, 0.0230438, 0.0515276, 0)
(54235430, '(2022 AK)', 22.08, 0.101989, 0.228055, 0)
(54280679, '(2022 KX4)', 23.89, 0.0443154, 0.0990923, 0)
(54340445, '(2023 BO8)', 26.66, 0.0123753, 0.027672, 0)
(54433568, '(2024 GE3)', 26.08, 0.0161642, 0.0361443, 0)
(54442252, '(2024 JQ17)', 25.57, 0.0204435, 0.045713, 0)
(54527293, '(2025 FZ28)', 23.157, 0.0621091, 0.13888, 0)
(54528048, '(2025 HF12)', 22.864, 0.0710812, 0.158942, 0)
(54532867, '(2025 KJ)', 27.459, 0.00856554, 0.0191531, 0)
(2154276, '154276 (2002 SY50)', 17.64, 0.788052, 1.76214, 1)
(3278078, '(2005 JU81)', 21.79, 0.116561, 0.260639, 1)
(3669249, '(2014 HB124)', 23.02, 0.0661538, 0.147924, 0)
(3671001, '(2014 JA31)', 23.6, 0.0506471, 0.11325, 0)
(3672457, '(2014 KC39)', 23.3, 0.0581507, 0.130029, 0)
(3764838, '(2016 WR8)', 27.4, 0.00880146, 0.0196807, 0)
(3989263, '(2020 BP11)', 26.8, 0.0116026, 0.0259442, 0)
(54016782, '(2020 HM7)', 25.8, 0.0183889, 0.0411188, 0)
(54139088, '(2021 GM26)', 25.72, 0.019079, 0.0426619, 0)
(54219282, '(2021 VK10)', 26.04, 0.0164647, 0.0368163, 0)
(54278350, '(2022 JQ1)', 26.21, 0.0152249, 0.034044, 0)
(54358378, '(2023 JF2)', 24.61, 0.0318094, 0.0711279, 0)
(54383809, '(2023 RY15)', 27.98, 0.00673837, 0.0150675, 0)
(54492233, '(2024 TK20)', 21.36, 0.142087, 0.317717, 0)
(54533324, '(2025 KG3)', 25.479, 0.0213184, 0.0476694, 0)
(54533502, '(2025 KR4)', 25.946, 0.0171931, 0.038445, 0)
(2469494, '469494 (2002 XS40)', 20.0, 0.2658, 0.594347, 0)
(3353630, '(2006 UB64)', 20.6, 0.20163, 0.450858, 0)
(3544935, '(2010 PW58)', 21.7, 0.121494, 0.271669, 1)
(3648643, '(2013 SL20)', 24.62, 0.0316632, 0.0708011, 0)
(3720360, '(2015 KW121)', 26.1, 0.016016, 0.0358129, 0)
(3836927, '(2018 XM5)', 24.4, 0.0350393, 0.0783502, 0)
(54114211, '(2010 KD149)', 21.48, 0.134448, 0.300635, 1)
(54220860, '(2021 VQ22)', 25.93, 0.0173203, 0.0387293, 0)
(54224995, '(2021 WT2)', 24.13, 0.0396785, 0.0887238, 0)
(54268812, '(2022 GD1)', 25.07, 0.0257368, 0.0575493, 0)
(2620061, '620061 (2006 UB64)', 20.7, 0.192555, 0.430566, 0)
(54480235, '(2024 SG)', 27.25, 0.00943094, 0.0210882, 0)
(54527600, '(2025 HU3)', 25.722, 0.0190614, 0.0426226, 0)
(54527742, '(2025 HS5)', 25.47, 0.021407, 0.0478674, 0)
(54532862, '(2025 KD)', 25.825, 0.0181784, 0.0406481, 0)
(54532946, '(2025 KN)', 27.035, 0.0104125, 0.0232831, 0)
(54533162, '(2025 KJ2)', 24.681, 0.0307861, 0.0688399, 0)
(3484042, '(2009 YT6)', 21.14, 0.157237, 0.351593, 0)
(3719081, '(2015 HB177)', 24.6, 0.0319562, 0.0714562, 0)
(54249333, '(2022 ER2)', 22.12, 0.100128, 0.223893, 0)
(54322896, '(2022 VB)', 25.41, 0.0220067, 0.0492085, 0)
(54439712, '(2024 JO1)', 27.79, 0.00735453, 0.0164452, 0)
(54500489, '(2024 WL2)', 25.11, 0.0252671, 0.0564989, 0)
(54528529, '(2025 HD19)', 25.48, 0.0213086, 0.0476475, 0)
(54532561, '(2025 KA)', 25.932, 0.0173043, 0.0386937, 0)
(54533011, '(2025 KJ1)', 27.687, 0.00771179, 0.0172441, 0)
(54534227, '(2025 KE16)', 23.125, 0.0630311, 0.140942, 0)
(3529587, '(2010 LJ61)', 20.95, 0.171615, 0.383743, 0)
(3603627, '(2012 JN4)', 23.5, 0.0530341, 0.118588, 0)
(3692561, '(2014 TV)', 24.4, 0.0350393, 0.0783502, 0)
(3762462, '(2016 TH94)', 24.58, 0.0322519, 0.0721174, 0)
(3836275, '(2018 WK)', 27.1, 0.0101054, 0.0225964, 0)
(3841719, '(2019 JX1)', 29.1, 0.00402305, 0.0089958, 0)
(54016950, '(2020 HH10)', 23.7, 0.0483676, 0.108153, 0)
(54225508, '(2021 WR4)', 30.43, 0.00218049, 0.00487573, 0)
(54265621, '(2022 FJ1)', 25.54, 0.0207279, 0.046349, 0)
(54268819, '(2022 FY4)', 25.36, 0.0225193, 0.0503547, 0)
(54296726, '(2022 QX1)', 24.61, 0.0318094, 0.0711279, 0)
(54327902, '(2022 WN2)', 28.95, 0.00431077, 0.00963918, 0)
(54439716, '(2024 JQ1)', 27.09, 0.0101521, 0.0227007, 0)
(54494481, '(2024 UB1)', 28.47, 0.00537719, 0.0120238, 0)
(54532863, '(2025 KE)', 23.911, 0.0438889, 0.0981386, 0)
(54532957, '(2025 KY)', 27.245, 0.00945268, 0.0211368, 0)
(54532960, '(2025 KZ)', 26.393, 0.0139944, 0.0312925, 0)
(54533091, '(2025 KL1)', 24.276, 0.0370984, 0.0829545, 0)
(2065733, '65733 (1993 PC)', 18.4, 0.555335, 1.24177, 0)
(3752778, '(2016 JY5)', 27.1, 0.0101054, 0.0225964, 0)
(3752782, '(2016 JA6)', 26.3, 0.0146068, 0.0326618, 0)
(54134948, '(2021 GK2)', 23.3, 0.0581507, 0.130029, 0)
(54214721, '(2021 UY6)', 25.93, 0.0173203, 0.0387293, 0)
(54268817, '(2022 GJ1)', 24.11, 0.0400456, 0.0895447, 0)
(54305649, '(2022 SH4)', 25.62, 0.0199781, 0.0446725, 0)
(54339170, '(2023 AE2)', 25.09, 0.0255009, 0.0570217, 0)
(54341646, '(2023 DA)', 26.42, 0.0138215, 0.0309058, 0)
(54358783, '(2023 JV4)', 24.06, 0.0409784, 0.0916305, 0)

In [83]:
mycursor.execute('SELECT COUNT(*) FROM close_approach;')
for ele in mycursor:
    print(ele)

(10000,)

## 1. Count how many times each asteroid has approached Earth

In [216]:
# query = 'SELECT COUNT(*), id FROM asteroids GROUP BY id ORDER BY COUNT(*) DESC;'

# # Read the SQL query into a DataFrame
# df = pd.read_sql_query(query, myconnection)
# df

C:\Users\Ajay\AppData\Local\Temp\ipykernel_103656\1993736929.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, myconnection)

      COUNT(*)        id
0            8  54377574
1            7   3829424
2            7   3736497
3            7  54300837
4            7   3736807
...        ...       ...
6457         1   2162483
6458         1   2483432
6459         1   3283219
6460         1   3647011
6461         1  54049823

[6462 rows x 2 columns]

In [61]:
mycursor.execute('select count(*),id from asteroids group by id order by count(*) desc;')
for row in mycursor:
    print(row)

(8, 54377574)
(7, 3829424)
(7, 3736497)
(7, 54300837)
(7, 3736807)
(6, 3348144)
(6, 3550117)
(6, 54248949)
(6, 3683472)
(6, 54379768)
(6, 54433568)
(6, 2141531)
(6, 3744561)
(6, 54317205)
(6, 54336914)
(6, 54496852)
(6, 54382563)
(6, 54392070)
(6, 3552654)
(6, 3772995)
(6, 54393149)
(6, 54414145)
(6, 3410533)
(6, 3841761)
(6, 54496628)
(6, 2469219)
(6, 3738932)
(5, 54430725)
(5, 3789741)
(5, 54528919)
(5, 54385807)
(5, 54278350)
(5, 54049794)
(5, 54341646)
(5, 3678630)
(5, 3781304)
(5, 54053734)
(5, 54016433)
(5, 54433331)
(5, 54307197)
(5, 3771633)
(5, 54489181)
(5, 3802033)
(5, 54310126)
(5, 2523728)
(5, 3786458)
(5, 54483146)
(5, 3802577)
(5, 54053939)
(5, 54323527)
(5, 54327895)
(5, 2450300)
(5, 54387140)
(5, 54485072)
(5, 54321461)
(5, 54105522)
(5, 54467114)
(5, 3879168)
(5, 54190788)
(5, 3261681)
(5, 3472700)
(5, 54215205)
(5, 54194978)
(5, 54412460)
(5, 3843359)
(5, 54209488)
(5, 54215203)
(5, 54489167)
(5, 54338714)
(5, 54404389)
(5, 54316897)
(5, 54397463)
(5, 54220001)
(5, 54135787)
(5, 3802442)
(5, 3989355)
(5, 3418110)
(5, 54342587)
(5, 3485264)
(5, 3313739)
(5, 3644814)
(5, 3837907)
(5, 3837745)
(5, 54520800)
(5, 3742340)
(5, 54095181)
(5, 54124622)
(4, 3373919)
(4, 54144240)
(4, 54397455)
(4, 3719196)
(4, 3843051)
(4, 54492950)
(4, 54533420)
(4, 54445454)
(4, 54528330)
(4, 54533502)
(4, 3719730)
(4, 54145088)
(4, 2136818)
(4, 3618405)
(4, 54149827)
(4, 3836251)
(4, 2478784)
(4, 54441878)
(4, 2468540)
(4, 54305663)
(4, 3893720)
(4, 54177978)
(4, 54491554)
(4, 3956451)
(4, 54342224)
(4, 3989253)
(4, 54017684)
(4, 54110066)
(4, 54231259)
(4, 3825168)
(4, 3786459)
(4, 54190785)
(4, 54288619)
(4, 54340429)
(4, 54453741)
(4, 3837955)
(4, 3761647)
(4, 54304628)
(4, 3054338)
(4, 3989284)
(4, 3837605)
(4, 3825768)
(4, 3837949)
(4, 54137806)
(4, 2523605)
(4, 3702671)
(4, 3703372)
(4, 54496395)
(4, 54050999)
(4, 3767010)
(4, 54340154)
(4, 54480234)
(4, 54217199)
(4, 3836294)
(4, 54403791)
(4, 54467482)
(4, 54358249)
(4, 54248944)
(4, 54357980)
(4, 3767167)
(4, 3825135)
(4, 54266165)
(4, 54403806)
(4, 54224433)
(4, 3063789)
(4, 54051372)
(4, 54467481)
(4, 54319144)
(4, 54110065)
(4, 54235680)
(4, 54356391)
(4, 54465556)
(4, 3546741)
(4, 54190303)
(4, 54065916)
(4, 3388354)
(4, 3824978)
(4, 54190077)
(4, 54476945)
(4, 3728732)
(4, 54384198)
(4, 54317879)
(4, 54385810)
(4, 54202331)
(4, 54202334)
(4, 54265773)
(4, 54375851)
(4, 54016464)
(4, 54212589)
(4, 3799876)
(4, 3781897)
(4, 3648864)
(4, 3736412)
(4, 3655761)
(4, 3759293)
(4, 54226792)
(4, 54268089)
(4, 54185132)
(4, 3836114)
(4, 3750672)
(4, 54393696)
(4, 3694529)
(4, 3841509)
(4, 2208023)
(4, 2509505)
(4, 3552538)
(4, 3736387)
(4, 3740929)
(4, 3836416)
(4, 3274691)
(4, 3699886)
(4, 3647273)
(4, 3836286)
(4, 54230081)
(4, 3712947)
(4, 54016279)
(4, 54505715)
(4, 3797491)
(4, 3976539)
(4, 54016375)
(4, 54431498)
(4, 54016204)
(4, 54512606)
(4, 3736805)
(4, 3838888)
(4, 54509167)
(4, 2310842)
(4, 54426894)
(4, 3989652)
(4, 54017323)
(4, 3838835)
(4, 54123627)
(4, 54190080)
(4, 54288264)
(4, 54134547)
(4, 54130498)
(4, 54152389)
(4, 54268446)
(4, 3746620)
(4, 54375122)
(4, 54434765)
(4, 3754379)
(4, 54016520)
(4, 3565395)
(4, 54055040)
(4, 54150705)
(4, 3879285)
(4, 3781708)
(4, 2250680)
(4, 3843605)
(4, 3789720)
(4, 3712669)
(4, 3648469)
(4, 54087855)
(4, 3471518)
(4, 3063823)
(4, 2612197)
(4, 3591755)
(4, 54105103)
(3, 54439998)
(3, 54278174)
(3, 54017094)
(3, 54358912)
(3, 3830890)
(3, 3669249)
(3, 3989263)
(3, 3124996)
(3, 2612356)
(3, 54051164)
(3, 54482429)
(3, 3427460)
(3, 3720359)
(3, 54356988)
(3, 54427459)
(3, 54533158)
(3, 3831063)
(3, 54442252)
(3, 54528048)
(3, 3544935)
(3, 54114211)
(3, 54220860)
(3, 54439716)
(3, 54339170)
(3, 3293961)
(3, 54359833)
(3, 54521724)
(3, 54383301)
(3, 3092248)
(3, 54341549)
(3, 3759724)
(3, 3799765)
(3, 54016687)
(3, 54218583)
(3, 54225004)
(3, 54327909)
(3, 54447954)
(3, 3765003)
(3, 3906633)
(3, 54445312)
(3, 54533096)
(3, 54439324)
(3, 3621019)
(3, 3739247)
(3, 54370594)
(3, 3836411)
(3, 54053743)
(3, 54200305)
(3, 3763271)
(3, 54236616)
(3, 54330039)
(3, 3753797)
(3, 3670633)
(3, 54417172)
(3, 3548666)
(3, 54340710)
(3, 54110078)
(3, 54159398)
(3, 54160405)
(3, 54336908)
(3, 3532394)
(3, 54266166)
(3, 3767015)
(3, 54416849)
(3, 54190790)
(3, 54418648)
(3, 54216320)
(3, 3795036)
(3, 3662200)
(3, 2441987)
(3, 3381230)
(3, 54445623)
(3, 2322756)
(3, 3735686)
(3, 54441265)
(3, 54356994)
(3, 3295787)
(3, 3797674)
(3, 54356041)
(3, 54167176)
(3, 54222541)
(3, 54324411)
(3, 3972419)
(3, 54248971)
(3, 3092390)
(3, 3393818)
(3, 54122200)
(3, 54292324)
(3, 3517465)
(3, 54171999)
(3, 2163348)
(3, 2408982)
(3, 3520662)
(3, 3739705)
(3, 54191245)
(3, 54445920)
(3, 2162142)
(3, 3666783)
(3, 54017615)
(3, 3879278)
(3, 3788891)
(3, 54404085)
(3, 54212686)
(3, 54418267)
(3, 3789722)
(3, 54005663)
(3, 54087734)
(3, 3789401)
(3, 3608323)
(3, 3797753)
(3, 54496016)
(3, 54251534)
(3, 54331176)
(3, 54429762)
(3, 3781002)
(3, 3795122)
(3, 54465291)
(3, 2368184)
(3, 54323530)
(3, 54051260)
(3, 54377563)
(3, 3756946)
(3, 3840791)
(3, 3771023)
(3, 3559596)
(3, 3788075)
(3, 54248642)
(3, 3023012)
(3, 3989082)
(3, 3289173)
(3, 54423944)
(3, 3827310)
(3, 3840783)
(3, 54300305)
(3, 3656929)
(3, 3759721)
(3, 54306602)
(3, 3781451)
(3, 3686085)
(3, 3451790)
(3, 3991699)
(3, 54427465)
(3, 54383796)
(3, 54469024)
(3, 54305656)
(3, 54423318)
(3, 54195880)
(3, 54385785)
(3, 54468782)
(3, 3819564)
(3, 3728565)
(3, 54209306)
(3, 3092339)
(3, 3647027)
(3, 3836314)
(3, 54230077)
(3, 3831725)
(3, 54016324)
(3, 3893213)
(3, 54075314)
(3, 3836092)
(3, 3744994)
(3, 3143095)
(3, 54490515)
(3, 3869331)
(3, 54327900)
(3, 3835876)
(3, 54481754)
(3, 3873325)
(3, 54130760)
(3, 54185582)
(3, 54486934)
(3, 2523654)
(3, 54214066)
(3, 3767014)
(3, 54487286)
(3, 54235406)
(3, 54137511)
(3, 54289177)
(3, 3771018)
(3, 54486931)
(3, 3559911)
(3, 54416724)
(3, 54488497)
(3, 54101717)
(3, 2162080)
(3, 2085770)
(3, 54483138)
(3, 3387793)
(3, 3837954)
(3, 54006054)
(3, 54495415)
(3, 3838930)
(3, 54207058)
(3, 3989280)
(3, 54397142)
(3, 54404088)
(3, 3773922)
(3, 3719131)
(3, 54402642)
(3, 2144900)
(3, 3836098)
(3, 54016533)
(3, 54106538)
(3, 3838892)
(3, 54336956)
(3, 54316690)
(3, 3708945)
(3, 3843427)
(3, 54297618)
(3, 2434196)
(3, 3799712)
(3, 3457386)
(3, 54290859)
(3, 3651199)
(3, 3669149)
(3, 3733147)
(3, 3842752)
(3, 54099951)
(3, 54111254)
(3, 54352569)
(3, 2675214)
(3, 2138175)
(3, 3311964)
(3, 3558382)
(3, 3703013)
(3, 3789479)
(3, 3749034)
(3, 54432336)
(3, 2001865)
(3, 3791243)
(3, 3770142)
(3, 2011500)
(3, 2434051)
(3, 3307228)
(3, 54338715)
(3, 3824114)
(3, 54203035)
(3, 3788080)
(3, 54326659)
(3, 3445543)
(3, 54266174)
(3, 3893865)
(3, 2065717)
(3, 54356388)
(3, 3766164)
(3, 3893742)
(3, 2162215)
(3, 54117602)
(3, 54524982)
(3, 54249330)
(3, 2333755)
(3, 3836942)
(3, 54321820)
(3, 54224159)
(3, 54502468)
(3, 54051397)
(3, 54100697)
(3, 54101667)
(3, 54279841)
(3, 2471083)
(3, 3309092)
(3, 54506551)
(3, 3836859)
(3, 3764727)
(3, 3485263)
(3, 3713071)
(3, 3264188)
(3, 54335005)
(3, 3031176)
(3, 3795028)
(3, 3552578)
(3, 54509101)
(3, 3892161)
(3, 3337315)
(3, 3797689)
(3, 54419698)
(3, 3837539)
(3, 2162470)
(3, 2418265)
(3, 2422686)
(3, 2480883)
(3, 3177232)
(3, 54422164)
(3, 3767037)
(3, 54533159)
(3, 3986685)
(3, 54106083)
(3, 54521714)
(3, 3395309)
(3, 3840886)
(3, 54276249)
(3, 54467485)
(3, 54114201)
(3, 3412755)
(3, 2484462)
(3, 3599867)
(3, 3740825)
(3, 54178155)
(3, 54016363)
(3, 3766590)
(3, 54292217)
(3, 3797858)
(3, 54167171)
(3, 3709453)
(3, 54107791)
(3, 3638287)
(3, 54395028)
(3, 3719864)
(3, 3795152)
(3, 54013539)
(3, 3558372)
(3, 3989813)
(3, 54209222)
(3, 3743123)
(3, 3638286)
(3, 54123261)
(3, 3714452)
(3, 2673713)
(3, 54246616)
(3, 3672731)
(3, 3714554)
(3, 2592968)
(3, 3842637)
(3, 3771605)
(3, 3608622)
(3, 3788026)
(3, 54051103)
(3, 54207052)
(3, 3631790)
(3, 54496845)
(3, 3684344)
(3, 3747315)
(3, 3771609)
(3, 3843915)
(3, 54016321)
(3, 3748472)
(3, 54053794)
(3, 3835874)
(3, 3635077)
(3, 3306408)
(3, 54300597)
(3, 3713287)
(3, 54131485)
(3, 54143556)
(3, 54017258)
(3, 3666974)
(3, 54271303)
(3, 3844004)
(3, 3879543)
(3, 54200294)
(3, 54054595)
(3, 54269399)
(3, 54319164)
(3, 54441092)
(3, 54271304)
(3, 3774730)
(3, 54440653)
(3, 3179348)
(3, 54049856)
(3, 3472366)
(3, 54231711)
(3, 3715499)
(3, 54102019)
(3, 54156746)
(3, 3516633)
(3, 54016725)
(3, 54320182)
(3, 54147412)
(3, 54217965)
(3, 3843822)
(3, 3532401)
(3, 3608784)
(3, 3126183)
(3, 54247854)
(3, 54276734)
(3, 3873149)
(3, 54105524)
(3, 54317204)
(3, 3729233)
(3, 3781867)
(3, 3689018)
(3, 54278444)
(3, 3754269)
(3, 3674937)
(3, 3788165)
(3, 54087740)
(3, 54192756)
(3, 3426410)
(3, 2510190)
(3, 3836283)
(3, 54016332)
(3, 54380211)
(3, 54087437)
(3, 3724056)
(3, 54203005)
(3, 3701679)
(3, 54381323)
(3, 54161861)
(3, 3836413)
(3, 3293831)
(3, 3836857)
(3, 54157820)
(3, 54403397)
(3, 3623580)
(3, 3621568)
(3, 3607742)
(3, 54048867)
(3, 3727176)
(3, 3398090)
(3, 3754386)
(3, 54048847)
(3, 3893447)
(3, 3838249)
(3, 3843734)
(3, 54291608)
(3, 54111260)
(3, 3991578)
(3, 3741151)
(3, 3381260)
(3, 54125898)
(3, 3645042)
(3, 3727045)
(3, 3794969)
(3, 3297182)
(3, 54122192)
(3, 54236432)
(3, 54340474)
(3, 3831614)
(3, 54383794)
(3, 54416723)
(3, 54101721)
(3, 3387092)
(3, 54049356)
(3, 3689273)
(3, 3782020)
(3, 3869346)
(3, 2474158)
(3, 54382567)
(3, 3646649)
(3, 3683469)
(3, 54192216)
(3, 54225009)
(3, 3365921)
(3, 3781453)
(3, 3477703)
(3, 54205438)
(3, 3177202)
(3, 54305227)
(3, 3430304)
(3, 54416848)
(3, 54389194)
(3, 54206544)
(3, 54244784)
(3, 54317885)
(3, 3730575)
(3, 54101656)
(3, 54342171)
(3, 3732669)
(3, 3879547)
(3, 54110062)
(3, 54240412)
(3, 2452807)
(3, 3120862)
(3, 2518810)
(3, 3836049)
(3, 2488509)
(3, 3799748)
(3, 54235541)
(3, 3840124)
(3, 2108906)
(3, 3763339)
(3, 3789540)
(3, 3767008)
(3, 54139319)
(3, 54430947)
(3, 3893593)
(3, 2218017)
(3, 54136185)
(3, 3704156)
(3, 3768654)
(3, 3413165)
(3, 3632240)
(3, 3824058)
(3, 3893719)
(3, 3744560)
(3, 3788009)
(3, 3709135)
(3, 54360194)
(3, 54105561)
(3, 54235525)
(3, 54016442)
(3, 54335006)
(3, 3752777)
(3, 54110699)
(3, 2416224)
(3, 3727180)
(3, 54446789)
(3, 3673547)
(3, 2622577)
(3, 54054466)
(3, 3557197)
(2, 54138303)
(2, 54161068)
(2, 54352572)
(2, 3468431)
(2, 54317171)
(2, 3465236)
(2, 54216314)
(2, 54017159)
(2, 54203700)
(2, 54528922)
(2, 3092201)
(2, 2529951)
(2, 54016819)
(2, 54075984)
(2, 54138707)
(2, 54199511)
(2, 54354970)
(2, 54527656)
(2, 54528737)
(2, 54529312)
(2, 54533093)
(2, 3151655)
(2, 3736517)
(2, 54373546)
(2, 54529549)
(2, 54529811)
(2, 54490134)
(2, 54076351)
(2, 54216182)
(2, 54532400)
(2, 2154276)
(2, 3278078)
(2, 3671001)
(2, 3672457)
(2, 3764838)
(2, 54016782)
(2, 54139088)
(2, 54219282)
(2, 54358378)
(2, 54383809)
(2, 54492233)
(2, 54533324)
(2, 3776269)
(2, 54278143)
(2, 54524505)
(2, 3370167)
(2, 3843572)
(2, 2613726)
(2, 54532947)
(2, 3837644)
(2, 3841669)
(2, 54017665)
(2, 3550134)
(2, 3561029)
(2, 3672907)
(2, 3752080)
(2, 54357462)
(2, 54528926)
(2, 54532866)
(2, 54533098)
(2, 54533318)
(2, 3120863)
(2, 54527293)
(2, 3762462)
(2, 3836275)
(2, 54327902)
(2, 54494481)
(2, 54134948)
(2, 54376265)
(2, 54419815)
(2, 3525129)
(2, 54253541)
(2, 3824091)
(2, 54016732)
(2, 3458579)
(2, 3483206)
(2, 3721410)
(2, 54532951)
(2, 54533322)
(2, 54533414)
(2, 54533099)
(2, 3335046)
(2, 54087859)
(2, 54280484)
(2, 54296533)
(2, 3892775)
(2, 54533416)
(2, 54533421)
(2, 3727041)
(2, 3892309)
(2, 54290058)
(2, 54491558)
(2, 3767933)
(2, 54342179)
(2, 2162039)
(2, 2419624)
(2, 2424482)
(2, 3006207)
(2, 3841718)
(2, 54017402)
(2, 54017437)
(2, 54051081)
(2, 54533600)
(2, 54534234)
(2, 54224427)
(2, 2163696)
(2, 3753870)
(2, 3767164)
(2, 54106579)
(2, 3335422)
(2, 3735680)
(2, 54053762)
(2, 54280768)
(2, 54323533)
(2, 54445580)
(2, 54527657)
(2, 54533008)
(2, 54533166)
(2, 54533505)
(2, 3837653)
(2, 3591611)
(2, 54154694)
(2, 3831735)
(2, 54445843)
(2, 54017405)
(2, 54088813)
(2, 54301288)
(2, 3394071)
(2, 54159401)
(2, 54217964)
(2, 54532958)
(2, 3754389)
(2, 2329275)
(2, 3838020)
(2, 3842907)
(2, 54281981)
(2, 3655742)
(2, 54144921)
(2, 54533413)
(2, 54533602)
(2, 54533604)
(2, 54534098)
(2, 3842940)
(2, 3856703)
(2, 3771021)
(2, 3825507)
(2, 3892710)
(2, 3610030)
(2, 3713320)
(2, 3767261)
(2, 54049355)
(2, 3843455)
(2, 54393146)
(2, 54396393)
(2, 3545558)
(2, 3827174)
(2, 54317892)
(2, 3673598)
(2, 54210295)
(2, 3838186)
(2, 54105114)
(2, 54338890)
(2, 3740049)
(2, 3623673)
(2, 3699442)
(2, 3739261)
(2, 54529310)
(2, 3483327)
(2, 54402141)
(2, 3021049)
(2, 3365951)
(2, 3605902)
(2, 3607527)
(2, 54016228)
(2, 54054405)
(2, 54235433)
(2, 2612094)
(2, 2138205)
(2, 3616348)
(2, 3836972)
(2, 3837864)
(2, 3842764)
(2, 54289511)
(2, 54296728)
(2, 54423947)
(2, 54517090)
(2, 3785933)
(2, 54075551)
(2, 2437844)
(2, 54404086)
(2, 3772982)
(2, 54374826)
(2, 2456938)
(2, 3733862)
(2, 54376019)
(2, 3788088)
(2, 3893382)
(2, 54489663)
(2, 3943319)
(2, 3408585)
(2, 3472374)
(2, 3789721)
(2, 54099344)
(2, 3261769)
(2, 3735684)
(2, 54100692)
(2, 3463759)
(2, 3684730)
(2, 3445544)
(2, 3837860)
(2, 54431500)
(2, 3644769)
(2, 3674427)
(2, 3754252)
(2, 3842883)
(2, 54096095)
(2, 54269054)
(2, 54346963)
(2, 54373542)
(2, 54088800)
(2, 54285294)
(2, 54380887)
(2, 3779048)
(2, 2584604)
(2, 54376437)
(2, 3409438)
(2, 3745831)
(2, 3769881)
(2, 54016935)
(2, 3565066)
(2, 3638434)
(2, 3836206)
(2, 54381324)
(2, 3798987)
(2, 3942363)
(2, 54341464)
(2, 54518040)
(2, 2499986)
(2, 54330738)
(2, 3751530)
(2, 54055082)
(2, 54289510)
(2, 54376436)
(2, 54521611)
(2, 2367390)
(2, 3170242)
(2, 3781043)
(2, 2475534)
(2, 3511111)
(2, 3768620)
(2, 54243727)
(2, 3725653)
(2, 3653259)
(2, 3756911)
(2, 3893274)
(2, 54048903)
(2, 54470425)
(2, 3441093)
(2, 3333611)
(2, 54050997)
(2, 3626084)
(2, 3766434)
(2, 3879320)
(2, 54195868)
(2, 54294031)
(2, 2087309)
(2, 2513138)
(2, 3606269)
(2, 3843335)
(2, 3986776)
(2, 54051183)
(2, 54355033)
(2, 54193344)
(2, 54049357)
(2, 54293111)
(2, 54431587)
(2, 3601337)
(2, 3743127)
(2, 3750660)
(2, 54193343)
(2, 54378777)
(2, 3426239)
(2, 3838124)
(2, 54051038)
(2, 54339762)
(2, 3732907)
(2, 3757298)
(2, 3781311)
(2, 54296749)
(2, 54341459)
(2, 54341643)
(2, 54471067)
(2, 3841534)
(2, 54051297)
(2, 3512702)
(2, 3600106)
(2, 3639439)
(2, 3797751)
(2, 54178640)
(2, 54297317)
(2, 54377576)
(2, 3760680)
(2, 3826685)
(2, 3837603)
(2, 3147579)
(2, 54256791)
(2, 54104721)
(2, 54253543)
(2, 54423312)
(2, 54255061)
(2, 54435203)
(2, 3721289)
(2, 3884012)
(2, 54526031)
(2, 2488615)
(2, 3596262)
(2, 54385792)
(2, 2098943)
(2, 54272760)
(2, 3759669)
(2, 3738913)
(2, 54391031)
(2, 3136724)
(2, 3404165)
(2, 3840866)
(2, 2040263)
(2, 3843884)
(2, 54265631)
(2, 54372216)
(2, 54426750)
(2, 3761354)
(2, 3878570)
(2, 54016678)
(2, 54350901)
(2, 3843107)
(2, 3799253)
(2, 54235435)
(2, 54297802)
(2, 3043931)
(2, 3788903)
(2, 54053846)
(2, 54130487)
(2, 54178641)
(2, 54467484)
(2, 3545713)
(2, 54104254)
(2, 54469533)
(2, 54510155)
(2, 54467973)
(2, 3893638)
(2, 2434344)
(2, 3752409)
(2, 54349260)
(2, 3046125)
(2, 3766128)
(2, 54212691)
(2, 3727640)
(2, 54055107)
(2, 54383282)
(2, 3623681)
(2, 3744562)
(2, 54143413)
(2, 54339977)
(2, 2669608)
(2, 2455594)
(2, 3339664)
(2, 54481742)
(2, 54525863)
(2, 3735181)
(2, 3843622)
(2, 54132075)
(2, 54524973)
(2, 54110086)
(2, 54217963)
(2, 54308062)
(2, 54379927)
(2, 54393981)
(2, 54384760)
(2, 2350523)
(2, 3014110)
(2, 3295789)
(2, 3655971)
(2, 3748492)
(2, 54217983)
(2, 54276656)
(2, 54392428)
(2, 54434347)
(2, 3791345)
(2, 54271308)
(2, 3827143)
(2, 3830496)
(2, 3005969)
(2, 54322888)
(2, 3838859)
(2, 3989344)
(2, 54326957)
(2, 54483147)
(2, 3799312)
(2, 54469029)
(2, 3781988)
(2, 3782063)
(2, 3879167)
(2, 54321452)
(2, 54385233)
(2, 54305651)
(2, 3840718)
(2, 3471356)
(2, 3730802)
(2, 3994621)
(2, 54253542)
(2, 54391010)
(2, 3137864)
(2, 3449749)
(2, 3547175)
(2, 3830881)
(2, 54312938)
(2, 54469548)
(2, 54499681)
(2, 54378891)
(2, 3427459)
(2, 3720000)
(2, 54201807)
(2, 2369986)
(2, 3092506)
(2, 3746623)
(2, 54051291)
(2, 3878561)
(2, 54265894)
(2, 54352299)
(2, 3611402)
(2, 54202333)
(2, 54312823)
(2, 3838904)
(2, 54486545)
(2, 54496027)
(2, 3163746)
(2, 3388887)
(2, 3612164)
(2, 3789121)
(2, 3831876)
(2, 54051399)
(2, 3785769)
(2, 54317172)
(2, 3430307)
(2, 3694787)
(2, 3799834)
(2, 54392060)
(2, 2461397)
(2, 54495421)
(2, 3625730)
(2, 3792461)
(2, 54136202)
(2, 54317870)
(2, 54330041)
(2, 54357208)
(2, 54147685)
(2, 54360089)
(2, 54396392)
(2, 54439707)
(2, 3879228)
(2, 54051126)
(2, 3735998)
(2, 54316911)
(2, 3837541)
(2, 3878603)
(2, 54320707)
(2, 2436763)
(2, 3691090)
(2, 3720002)
(2, 3825235)
(2, 54246999)
(2, 54276379)
(2, 54383297)
(2, 54433329)
(2, 54494719)
(2, 3840842)
(2, 3879241)
(2, 54340273)
(2, 3773650)
(2, 3799826)
(2, 54412463)
(2, 3557536)
(2, 54102519)
(2, 54219796)
(2, 3092342)
(2, 3611399)
(2, 3803910)
(2, 54278317)
(2, 54075592)
(2, 54264233)
(2, 54322245)
(2, 3672459)
(2, 3986735)
(2, 54006023)
(2, 54433731)
(2, 3164410)
(2, 54210293)
(2, 54329643)
(2, 54347915)
(2, 54465827)
(2, 3599872)
(2, 3843536)
(2, 54309248)
(2, 54184275)
(2, 54216378)
(2, 54402652)
(2, 2306383)
(2, 3117427)
(2, 3401433)
(2, 3427458)
(2, 3892708)
(2, 54321095)
(2, 54357276)
(2, 3309832)
(2, 2164294)
(2, 3692560)
(2, 54214728)
(2, 54497569)
(2, 3742875)
(2, 54378342)
(2, 54402369)
(2, 54495687)
(2, 2426082)
(2, 3789618)
(2, 3878564)
(2, 54099613)
(2, 54214047)
(2, 2348306)
(2, 3576729)
(2, 3617076)
(2, 54144286)
(2, 54268448)
(2, 2138852)
(2, 3986725)
(2, 3359094)
(2, 3767009)
(2, 54017226)
(2, 54415885)
(2, 3989190)
(2, 2481127)
(2, 54225722)
(2, 3836124)
(2, 2363505)
(2, 2447221)
(2, 3736207)
(2, 3788048)
(2, 3792460)
(2, 3797899)
(2, 54142836)
(2, 3587872)
(2, 3634154)
(2, 3892813)
(2, 54276986)
(2, 3620868)
(2, 3709924)
(2, 3714590)
(2, 3745032)
(2, 3564040)
(2, 3644727)
(2, 3691160)
(2, 3763286)
(2, 3836261)
(2, 54321082)
(2, 54336806)
(2, 2003361)
(2, 3733861)
(2, 3825011)
(2, 54093082)
(2, 54520815)
(2, 3736682)
(2, 3789748)
(2, 2376879)
(2, 3739413)
(2, 54214719)
(2, 3409433)
(2, 54087860)
(2, 54218575)
(2, 54330040)
(2, 54087667)
(2, 3475235)
(2, 3764824)
(2, 3840727)
(2, 54329635)
(2, 3714458)
(2, 54336807)
(2, 54380898)
(2, 3143112)
(2, 3824065)
(2, 54131346)
(2, 54336638)
(2, 2446924)
(2, 3358115)
(2, 3393819)
(2, 3445538)
(2, 3553704)
(2, 54137799)
(2, 54196856)
(2, 54280492)
(2, 54399995)
(2, 3548081)
(2, 3719242)
(2, 2706765)
(2, 3394543)
(2, 3836709)
(2, 54278177)
(2, 3774688)
(2, 54224161)
(2, 54414131)
(2, 2329571)
(2, 3774381)
(2, 3843708)
(2, 54329631)
(2, 3826807)
(2, 3836849)
(2, 3150194)
(2, 3459484)
(2, 54016448)
(2, 54375900)
(2, 2230599)
(2, 3359279)
(2, 3605576)
(2, 3638335)
(2, 3724948)
(2, 54218574)
(2, 3905999)
(2, 54184284)
(2, 3752788)
(2, 3943342)
(2, 3989266)
(2, 54360002)
(2, 54143420)
(2, 3157332)
(2, 3907553)
(2, 54013568)
(2, 54432219)
(2, 54279762)
(2, 3619732)
(2, 3736390)
(2, 3796295)
(2, 54292846)
(2, 54413284)
(2, 54161708)
(2, 54423050)
(2, 2054071)
(2, 3837721)
(2, 54229474)
(2, 54228826)
(2, 3330155)
(2, 3092220)
(2, 3446391)
(2, 3824972)
(2, 3959223)
(2, 3102728)
(2, 3753371)
(2, 3893730)
(2, 3989336)
(2, 54152388)
(2, 54192218)
(2, 54210564)
(2, 54296365)
(2, 54514905)
(2, 2088213)
(2, 3739257)
(2, 3370278)
(2, 3841630)
(2, 2438430)
(2, 3842591)
(2, 3791342)
(2, 3879723)
(2, 3760536)
(2, 3991612)
(2, 2484403)
(2, 3986848)
(2, 3600236)
(2, 3799759)
(2, 54457673)
(2, 2418849)
(2, 3511834)
(2, 3102731)
(2, 3553148)
(2, 3595775)
(2, 3797905)
(2, 3802063)
(2, 3825138)
(2, 2620103)
(2, 54376464)
(2, 2668499)
(2, 2259221)
(2, 3022973)
(2, 54297798)
(2, 54417548)
(2, 54417555)
(2, 54427938)
(2, 3555769)
(2, 54293876)
(2, 54516463)
(2, 3336867)
(2, 54352301)
(2, 3825245)
(2, 3841624)
(2, 3893275)
(2, 54105990)
(2, 54438673)
(2, 3749345)
(2, 3792468)
(2, 2494975)
(2, 3767036)
(2, 54160403)
(2, 3718321)
(2, 3283218)
(2, 3559843)
(2, 3797456)
(2, 3484581)
(2, 2526798)
(2, 54356031)
(2, 3795086)
(2, 54421395)
(2, 3627115)
(2, 3831212)
(2, 2495930)
(2, 3266031)
(2, 3654336)
(2, 54516185)
(2, 54332005)
(2, 54360090)
(2, 2509352)
(2, 3147552)
(2, 3177193)
(2, 3557082)
(2, 3645791)
(2, 3767163)
(2, 54106310)
(2, 54354676)
(2, 3829436)
(2, 54203710)
(2, 54419345)

In [252]:
mycursor.execute('select count(*),id from asteroids group by id order by count(*) desc;')
result=mycursor.fetchall()
df=pd.DataFrame(result,columns=[i[0]for i in mycursor.description])

print(df)

      count(*)        id
0            8  54377574
1            7   3829424
2            7   3736497
3            7  54300837
4            7   3736807
...        ...       ...
6457         1   2162483
6458         1   2483432
6459         1   3283219
6460         1   3647011
6461         1  54049823

[6462 rows x 2 columns]

In [51]:
mycursor.description

(('count(*)', 8, None, 21, 21, 0, False), ('id', 3, None, 11, 11, 0, True))

## 2. Average velocity of each asteroid over multiple approaches

In [71]:
mycursor.execute('select avg(relative_velocity_kmph) as Average_velocity, count(*), neo_reference_id from close_approach group by neo_reference_id;')
result=mycursor.fetchall()
df1=pd.DataFrame(result, columns=[i[0] for i in mycursor.description])
df1

      Average_velocity  count(*)  neo_reference_id
0         60167.741211         4           3373919
1         48556.402344         1          54110077
2         58390.294922         2          54138303
3         80174.548828         4          54144240
4         16418.460938         1          54421069
...                ...       ...               ...
6457      83119.273438         1           2162483
6458      88211.945312         1           2483432
6459      18496.066406         1           3283219
6460      14268.454102         1           3647011
6461      12271.110352         1          54049823

[6462 rows x 3 columns]

## 3. List top 10 fastest asteroids

In [73]:
mycursor.description

(('Average_velocity', 5, None, 23, 23, 31, True),
 ('count(*)', 8, None, 21, 21, 0, False),
 ('neo_reference_id', 3, None, 11, 11, 0, True))

In [79]:
mycursor.execute('select relative_velocity_kmph, neo_reference_id from close_approach order by relative_velocity_kmph desc limit 10; ')
result=mycursor.fetchall()
df2=pd.DataFrame(result, columns=[i[0] for i in mycursor.description])
df2

   relative_velocity_kmph  neo_reference_id
0                186136.0           2504181
1                169787.0           2394130
2                163863.0           3639550
3                162471.0          54239841
4                160285.0          54203006
5                159112.0           3472374
6                157682.0          54194346
7                151120.0           3409988
8                149521.0           3588900
9                149438.0           3837511

## 4. Find potentially hazardous asteroids that have approached Earth more than 3 times

In [111]:
mycursor.execute('''select a.id,a.name,a.Hazard,count(a.id)as approached_count from asteroids as a join close_approach as c on 
a.id=c.neo_reference_id where Hazard=True group by a.id,a.name having count(a.id)>3 order by count(a.id)desc;''')
resultt=mycursor.fetchall()
df4=pd.DataFrame(resultt, columns=(i[0]for i in mycursor.description))
print(df4)

           id                name  Hazard  approached_count
0     2450300  450300 (2004 QD14)       1                25
1    54441878         (2024 JR16)       1                16
2    54465556          (2024 NO5)       1                16
3     2208023  208023 (1999 AQ10)       1                16
4     2250680   250680 (2005 QC5)       1                16
..        ...                 ...     ...               ...
165   3719183          (2015 JD1)       1                 4
166   3102694         (2001 XP31)       1                 4
167   3770288        (2017 DN109)       1                 4
168   3549391        (2010 TU149)       1                 4
169   3563860           (2011 HT)       1                 4

[170 rows x 4 columns]

## 5. Find the month with the most asteroid approaches

In [114]:
mycursor.execute('''select count(month(close_approach_date))as total_approach,month(close_approach_date)as Month 
 from close_approach group by month(close_approach_date) order by total_approach desc limit 1 ;''')
resultt=mycursor.fetchall()
df5=pd.DataFrame(resultt, columns=(i[0]for i in mycursor.description))
print(df5)

   total_approach  Month
0            1231      5

## 6. Get the asteroid with the fastest ever approach speed

In [190]:
mycursor.execute(''' 
 select  neo_reference_id,  relative_velocity_kmph from close_approach
 order by relative_velocity_kmph desc limit 1;''')
resultt=mycursor.fetchall()
df6=pd.DataFrame(resultt, columns=(i[0]for i in mycursor.description))
print(df6)

   neo_reference_id  relative_velocity_kmph
0           2504181                186136.0

## 7.Sort asteroids by maximum estimated diameter (descending)

In [192]:
mycursor.execute('''
select id,name,estimated_diameter_max_km from asteroids order by estimated_diameter_max_km desc;
''')
result=mycursor.fetchall()
df7=pd.DataFrame(result, columns=(i[0] for i in mycursor.description))
print(df7)

            id                 name  estimated_diameter_max_km
0      2000433   433 Eros (A898 PA)                  49.208500
1      2066146     66146 (1998 TU3)                   7.980680
2      2004953       4953 (1990 MU)                   6.223580
3      2138205  138205 (2000 EZ148)                   5.702170
4      2138205  138205 (2000 EZ148)                   5.702170
...        ...                  ...                        ...
9995  54423319         (2021 UO120)                   0.002618
9996   3556206           (2011 CQ1)                   0.002260
9997   3556206           (2011 CQ1)                   0.002260
9998   3837685           (2019 AS5)                   0.002061
9999  54473959          (2024 RC42)                   0.001986

[10000 rows x 3 columns]

## 8. An asteroid whose closest approach is getting nearer over time(Hint: Use ORDER BY close_approach_date and look at miss_distance).

In [232]:
mycursor.execute('''select name,close_approach_date, miss_distance_km from asteroids join close_approach
on id=neo_reference_id order by miss_distance_km limit 1;''')
result=mycursor.fetchall()
df8=pd.DataFrame(result, columns=(i[0] for i in mycursor.description))
print(df8)

        name close_approach_date  miss_distance_km
0  (2025 KF)          2025-05-21          115126.0

## 9. Display the name of each asteroid along with the date and miss distance of its closest approach to Earth.

In [230]:
mycursor.execute('''select name, max(close_approach_date),min(miss_distance_km) from asteroids join close_approach on id=neo_reference_id 
group by name order by min(miss_distance_km),max(close_approach_date) desc;''')
result=mycursor.fetchall()
df9=pd.DataFrame(result, columns=(i[0]for i in mycursor.description))
print(df9)

                  name max(close_approach_date)  min(miss_distance_km)
0            (2025 KF)               2025-05-21               115126.0
1           (2025 KF2)               2025-05-21               139791.0
2           (2025 KS1)               2025-05-22               146113.0
3            (2025 LB)               2025-06-04               151998.0
4           (2025 KQ4)               2025-05-26               162057.0
...                ...                      ...                    ...
6457  497245 (2005 FH)               2027-03-07             74733300.0
6458         (2014 FP)               2027-02-06             74750200.0
6459       (2017 WG15)               2026-05-10             74755100.0
6460        (2023 HK5)               2026-07-17             74769600.0
6461        (2018 RT7)               2026-03-15             74776600.0

[6462 rows x 3 columns]

## 10. List names of asteroids that approached Earth with velocity > 50,000 km/h

In [197]:
mycursor.execute('''SELECT name,relative_velocity_kmph FROM asteroids 
JOIN close_approach  ON id = neo_reference_id
WHERE relative_velocity_kmph > 50000;''')
result=mycursor.fetchall()
df10=pd.DataFrame(result, columns=(i[0] for i in mycursor.description))
print(df10)

                    name  relative_velocity_kmph
0             (2007 GW4)                 53921.7
1             (2007 GW4)                 70081.1
2             (2007 GW4)                 55400.3
3             (2007 GW4)                 61267.8
4            (2021 GT16)                 64525.8
...                  ...                     ...
8014   162483 (2000 PJ5)                 83119.3
8015  483432 (2001 DF47)                 88211.9
8016          (2020 KP7)                 73841.1
8017          (2020 KP7)                 68193.8
8018          (2020 KP7)                 55915.5

[8019 rows x 2 columns]

## 11.Count how many approaches happened per month

In [254]:
mycursor.execute('''select count(month(close_approach_date)),month(close_approach_date) from close_approach group by month(close_approach_date);''')
result=mycursor.fetchall()
df11=pd.DataFrame(result, columns=(i[0] for i in mycursor.description))
print(df11)

    count(month(close_approach_date))  month(close_approach_date)
0                                1231                           5
1                                 986                           6
2                                 959                           7
3                                 707                           8
4                                 748                           9
5                                 914                          10
6                                 765                          11
7                                 721                          12
8                                 743                           1
9                                 711                           2
10                                780                           3
11                                735                           4

## 12.Find asteroid with the highest brightness (lowest magnitude value)

In [203]:
mycursor.execute('select * from asteroids order by absolute_magnitude_h limit 1;')
result=mycursor.fetchall()
df12=pd.DataFrame(result, columns=(i[0]for i in mycursor.description))
print(df12)

        id                name  absolute_magnitude_h  \
0  2000433  433 Eros (A898 PA)                 10.41

   estimated_diameter_min_km  estimated_diameter_max_km  Hazard
0                    22.0067                    49.2085       0

## 13.Get number of hazardous vs non-hazardous asteroids

In [206]:
mycursor.execute('SELECT hazard AS hazard_status,COUNT(*) FROM asteroids GROUP BY hazard;')
result=mycursor.fetchall()
df13=pd.DataFrame(result, columns=(i[0]for i in mycursor.description))
print(df13)

   hazard_status  COUNT(*)
0              0      9187
1              1       813

## 14.Find asteroids that passed closer than the Moon (lesser than 1 LD), along with their close approach date and distance.

In [222]:
mycursor.execute('''select id, close_approach_date, miss_distance_lunar from asteroids join
close_approach on id=neo_reference_id where miss_distance_lunar <1;''')
result=mycursor.fetchall()
df14=pd.DataFrame(result, columns=(i[0]for i in mycursor.description))
df14.drop_duplicates(inplace=True)
print(df14)

          id close_approach_date  miss_distance_lunar
0   54528735          2025-05-01             0.518955
1   54528916          2025-05-01             0.451765
2   54528737          2025-05-08             0.953021
6   54532864          2025-05-21             0.299363
7   54533161          2025-05-21             0.363499
8   54533098          2025-05-22             0.379938
10  54533318          2025-05-22             0.955938
12  54533007          2025-05-23             0.501840
13  54533422          2025-05-23             0.727127
18  54533501          2025-05-26             0.421397
19  54533415          2025-05-28             0.883328
20  54534093          2025-06-04             0.395241
21   3634154          2026-04-14             0.677452

## 15. Find asteroids that came within 0.05 AU(astronomical distance)

In [214]:
mycursor.execute('select neo_reference_id, astronomical from close_approach where astronomical <0.05;')
result=mycursor.fetchall()
df15=pd.DataFrame(result, columns=(i[0]for i in mycursor.description))
print(df15)

     neo_reference_id  astronomical
0            54421069      0.024301
1            54527149      0.028799
2            54528735      0.001334
3            54528916      0.001161
4            54439998      0.019404
..                ...           ...
413           3837605      0.033049
414           3976539      0.043551
415          54373753      0.020550
416          54327885      0.022252
417          54192165      0.026572

[418 rows x 2 columns]

In [234]:
## Own queries

In [ ]:
# 1. Top 5 potentially hazardous asteroids details with the recent dates

In [236]:
mycursor.execute("""select id,name,close_approach_date,relative_velocity_kmph,hazard from asteroids join close_approach
on id=neo_reference_id where hazard=1 order by close_approach_date desc limit 10;""")
result=mycursor.fetchall()
df16=pd.DataFrame(result, columns=(i[0]for i in mycursor.description))
print(df16)

        id                name close_approach_date  relative_velocity_kmph  \
0  2613569   613569 (2006 TU7)          2027-07-29                 78525.1
1  3350633          (2006 TU7)          2027-07-29                 78525.1
2  2162000    162000 (1990 OS)          2027-07-29                 49415.5
3  3838082          (2019 BF5)          2027-07-28                 80138.5
4  3184160          (2004 MX2)          2027-07-28                 62383.3
5  2483432  483432 (2001 DF47)          2027-07-27                 88211.9
6  3989242         (2020 BN10)          2027-07-21                 43488.0
7  3989242         (2020 BN10)          2027-07-21                 43488.0
8  3711785        (2015 DP155)          2027-07-20                 54388.8
9  3711785        (2015 DP155)          2027-07-20                 54388.8

   hazard
0       1
1       1
2       1
3       1
4       1
5       1
6       1
7       1
8       1
9       1

In [ ]:
# 2. Getting the details of the same asteroid count and their names

In [238]:
mycursor.execute('select id,name,count(id) from asteroids group by id,name order by count(id) desc;')
result=mycursor.fetchall()
df17=pd.DataFrame(result, columns=(i[0]for i in mycursor.description))
print(df17)

            id                name  count(id)
0     54377574          (2023 QB2)          8
1      3829424          (2018 RO5)          7
2      3736497        (2015 XF261)          7
3     54300837         (2022 QB37)          7
4      3736807           (2015 YA)          7
...        ...                 ...        ...
6457   2406952    406952 (2009 KJ)          1
6458   3748467         (2016 FP12)          1
6459   3774001           (2017 HU)          1
6460   3825010          (2018 KW1)          1
6461   2453707  453707 (2010 XY72)          1

[6462 rows x 3 columns]

In [ ]:
3.Getting the description about the particular asteroid name

In [242]:
mycursor.execute('''select id, name,close_approach_date,relative_velocity_kmph,hazard from asteroids join close_approach
on id=neo_reference_id where name='(2018 KW1)';''')
result=mycursor.fetchall()
df18=pd.DataFrame(result,columns=(i[0]for i in mycursor.description))
print(df18)

        id        name close_approach_date  relative_velocity_kmph  hazard
0  3825010  (2018 KW1)          2027-04-27                 48713.1       0

In [ ]:
#4. Counting how many approaches occurred Each Year

In [244]:
mycursor.execute('select year(close_approach_date),count(*) from close_approach group by year(close_approach_date);')
result=mycursor.fetchall()
df19=pd.DataFrame(result,columns=(i[0]for i in mycursor.description))
df19

   year(close_approach_date)  count(*)
0                       2025      3017
1                       2026      4525
2                       2027      2458

In [ ]:
#5.getting details of Most Hazardous Asteroid in 2025

In [250]:
mycursor.execute('''select id,name,close_approach_date,relative_velocity_kmph,miss_distance_km,hazard from asteroids join close_approach
on id=neo_reference_id where hazard=1 and year(close_approach_date)=2025;''')
result=mycursor.fetchall()
df20=pd.DataFrame(result, columns=(i[0]for i in mycursor.description))
df20

,id,name,close_approach_date,relative_velocity_kmph,miss_distance_km,hazard
0,54352572,(2023 FC6),2025-05-03,41249.9,9694860.0,1
1,54352572,(2023 FC6),2025-05-03,41249.9,9694860.0,1
2,3831479,(2018 TF3),2025-05-02,86030.0,16396400.0,1
3,54239841,(2022 BH1),2025-05-02,162471.0,72780500.0,1
4,2529951,529951 (2010 UD),2025-05-06,52120.7,68098500.0,1
...,...,...,...,...,...,...
350,54514905,(2025 AK2),2025-12-25,37717.4,28825200.0,1
351,54514905,(2025 AK2),2025-12-25,37717.4,28825200.0,1
352,2220839,220839 (2004 VA),2025-12-30,44230.4,14352200.0,1
353,2418849,418849 (2008 WM64),2025-12-31,81503.6,56826500.0,1
354,2418849,418849 (2008 WM64),2025-12-31,81503.6,56826500.0,1

In [ ]:
myconnection.close()